# Generated by Django 4.0 on 2022-06-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'full_name',
                    models.CharField(max_length=120, verbose_name='Full Name'),
                ),
                ('job', models.CharField(max_length=120, verbose_name='Job')),
                ('email', models.EmailField(max_length=254)),
                ('domain_name', models.URLField()),
                ('phone_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('integer', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=120)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='auth.user',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('order', models.PositiveIntegerField()),
                ('column_name', models.CharField(max_length=120)),
                (
                    'column_type',
                    models.CharField(
                        choices=[
                            ('Full Name', 'Full Name'),
                            ('Job', 'Job'),
                            ('Email', 'Email'),
                            ('Domain Name', 'Domain Name'),
                            ('Phone Number', 'Phone Number'),
                            ('Company Name', 'Company Name'),
                            ('Text', 'Text'),
                            ('Integer', 'Integer'),
                            ('Address', 'Address'),
                            ('Date', 'Date'),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    'data_set',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='csv_generator.dataset',
                    ),
                ),
            ],
        ),
    ]
