name: CSV Generator CI
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test_app:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: djangodb
          POSTGRES_PASSWORD: dj_pass123
          POSTGRES_USER: dj_user
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 2s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ github.sha }}
          path: |
            .cache
            node_modules
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Tune database
        env:
          PGHOST: localhost
          PGUSER: dj_user
          PGDATABASE: djangodb
          PGPORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          psql -c 'ALTER SYSTEM SET fsync=off;'
          psql -c 'ALTER SYSTEM SET synchronous_commit=off;'
          psql -c 'ALTER SYSTEM SET full_page_writes=off;'
      - name: api-tests
        working-directory: ./app
        run: |
          python -m pip install --upgrade pip
          make dev-requirements coverage
        env:
          DJANGODB_URL: postgres://dj_user:dj_pass123@localhost/djangodb